[[quotes]]
japanese = "戦わなければ勝てない"
anime = "Attack on Titan"
romaji = "Tatakawanakereba katenai"
character = "Eren Yeager"
quote = "You can’t win if you don’t fight"
image = "assets/aot.jpg"

[[quotes]]
japanese = "海賊王に俺はなる"
anime = "One Piece"
romaji = "Kaizokuō ni ore wa naru"
character = "Monkey D. Luffy"
quote = "I’m gonna be king of the pirates"
image = "assets/one_piece.jpg"

[[quotes]]
japanese = "まっすぐ自分の言葉は曲げねえ…オレの忍道だ"
anime = "Naruto"
romaji = "Massugu jibun no kotoba wa magenee, ore no nindou da"
character = "Naruto Uzumaki"
quote = "I won’t go back on my words. That’s my Ninja way"
image = "assets/naruto.jpg"
