[ui]
show_instructions = true

[ui.ascii]
target_width = 30
char_aspect = 0.5
detail_x = 2
detail_y = 2
gradient = "$@B%8&WM#*oahkbdpqwmZO0QLCJUYXzcvunxrjft/\\|()1{}[]?-_+~<>i!lI;:,\"^`'. "

[ui.colors]
anime = "yellow"
character = "cyan"
japanese = "green"
quote = "white"
count = "gray"
instructions = "blue"
